-- AUTOGENERATED FILE - DO NOT EDIT
-- AWS Service: kms

local common = require("nvim-aws.common")

--- AWS kms service functions
local M = {}

--- AWS kms cancel-key-deletion operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.cancel_key_deletion(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "cancel-key-deletion" }, input, callbacks)
end

--- AWS kms connect-custom-key-store operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.connect_custom_key_store(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "connect-custom-key-store" }, input, callbacks)
end

--- AWS kms create-alias operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.create_alias(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "create-alias" }, input, callbacks)
end

--- AWS kms create-custom-key-store operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.create_custom_key_store(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "create-custom-key-store" }, input, callbacks)
end

--- AWS kms create-grant operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.create_grant(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "create-grant" }, input, callbacks)
end

--- AWS kms create-key operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.create_key(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "create-key" }, input, callbacks)
end

--- AWS kms decrypt operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.decrypt(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "decrypt" }, input, callbacks)
end

--- AWS kms delete-alias operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.delete_alias(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "delete-alias" }, input, callbacks)
end

--- AWS kms delete-custom-key-store operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.delete_custom_key_store(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "delete-custom-key-store" }, input, callbacks)
end

--- AWS kms delete-imported-key-material operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.delete_imported_key_material(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "delete-imported-key-material" }, input, callbacks)
end

--- AWS kms derive-shared-secret operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.derive_shared_secret(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "derive-shared-secret" }, input, callbacks)
end

--- AWS kms describe-custom-key-stores operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.describe_custom_key_stores(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "describe-custom-key-stores" }, input, callbacks)
end

--- AWS kms describe-key operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.describe_key(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "describe-key" }, input, callbacks)
end

--- AWS kms disable-key operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.disable_key(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "disable-key" }, input, callbacks)
end

--- AWS kms disable-key-rotation operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.disable_key_rotation(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "disable-key-rotation" }, input, callbacks)
end

--- AWS kms disconnect-custom-key-store operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.disconnect_custom_key_store(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "disconnect-custom-key-store" }, input, callbacks)
end

--- AWS kms enable-key operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.enable_key(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "enable-key" }, input, callbacks)
end

--- AWS kms enable-key-rotation operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.enable_key_rotation(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "enable-key-rotation" }, input, callbacks)
end

--- AWS kms encrypt operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.encrypt(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "encrypt" }, input, callbacks)
end

--- AWS kms generate-data-key operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.generate_data_key(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "generate-data-key" }, input, callbacks)
end

--- AWS kms generate-data-key-pair operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.generate_data_key_pair(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "generate-data-key-pair" }, input, callbacks)
end

--- AWS kms generate-data-key-pair-without-plaintext operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.generate_data_key_pair_without_plaintext(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "generate-data-key-pair-without-plaintext" }, input, callbacks)
end

--- AWS kms generate-data-key-without-plaintext operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.generate_data_key_without_plaintext(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "generate-data-key-without-plaintext" }, input, callbacks)
end

--- AWS kms generate-mac operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.generate_mac(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "generate-mac" }, input, callbacks)
end

--- AWS kms generate-random operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.generate_random(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "generate-random" }, input, callbacks)
end

--- AWS kms get-key-policy operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.get_key_policy(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "get-key-policy" }, input, callbacks)
end

--- AWS kms get-key-rotation-status operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.get_key_rotation_status(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "get-key-rotation-status" }, input, callbacks)
end

--- AWS kms get-parameters-for-import operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.get_parameters_for_import(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "get-parameters-for-import" }, input, callbacks)
end

--- AWS kms get-public-key operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.get_public_key(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "get-public-key" }, input, callbacks)
end

--- AWS kms import-key-material operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.import_key_material(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "import-key-material" }, input, callbacks)
end

--- AWS kms list-aliases operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.list_aliases(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "list-aliases" }, input, callbacks)
end

--- AWS kms list-grants operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.list_grants(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "list-grants" }, input, callbacks)
end

--- AWS kms list-key-policies operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.list_key_policies(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "list-key-policies" }, input, callbacks)
end

--- AWS kms list-key-rotations operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.list_key_rotations(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "list-key-rotations" }, input, callbacks)
end

--- AWS kms list-keys operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.list_keys(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "list-keys" }, input, callbacks)
end

--- AWS kms list-resource-tags operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.list_resource_tags(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "list-resource-tags" }, input, callbacks)
end

--- AWS kms list-retirable-grants operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.list_retirable_grants(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "list-retirable-grants" }, input, callbacks)
end

--- AWS kms put-key-policy operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.put_key_policy(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "put-key-policy" }, input, callbacks)
end

--- AWS kms re-encrypt operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.re_encrypt(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "re-encrypt" }, input, callbacks)
end

--- AWS kms replicate-key operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.replicate_key(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "replicate-key" }, input, callbacks)
end

--- AWS kms retire-grant operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.retire_grant(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "retire-grant" }, input, callbacks)
end

--- AWS kms revoke-grant operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.revoke_grant(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "revoke-grant" }, input, callbacks)
end

--- AWS kms rotate-key-on-demand operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.rotate_key_on_demand(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "rotate-key-on-demand" }, input, callbacks)
end

--- AWS kms schedule-key-deletion operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.schedule_key_deletion(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "schedule-key-deletion" }, input, callbacks)
end

--- AWS kms sign operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.sign(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "sign" }, input, callbacks)
end

--- AWS kms tag-resource operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.tag_resource(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "tag-resource" }, input, callbacks)
end

--- AWS kms untag-resource operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.untag_resource(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "untag-resource" }, input, callbacks)
end

--- AWS kms update-alias operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.update_alias(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "update-alias" }, input, callbacks)
end

--- AWS kms update-custom-key-store operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.update_custom_key_store(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "update-custom-key-store" }, input, callbacks)
end

--- AWS kms update-key-description operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.update_key_description(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "update-key-description" }, input, callbacks)
end

--- AWS kms update-primary-region operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.update_primary_region(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "update-primary-region" }, input, callbacks)
end

--- AWS kms verify operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.verify(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "verify" }, input, callbacks)
end

--- AWS kms verify-mac operation
--- @param input table|nil input parameters
--- @param callbacks table|nil {on_start = function(), on_stdout = function(line), on_stderr = function(err), on_exit = function(code)}
--- @return {success: boolean, data: table|nil, error: string|nil }|{success: boolean, job: Job }
function M.verify_mac(input, callbacks)
	return common.execute_aws_command_skeleton({ "kms", "verify-mac" }, input, callbacks)
end

return M
