-- AUTOGENERATED FILE - DO NOT EDIT
-- Generated: 2025-04-07 21:36:03
-- AWS Service: mailmanager

local common = require("nvim-aws.wrappers.common")

--- AWS MAILMANAGER service functions
local M = {}

--- Creates an import job for an address list
--- @param input table The input table for the create_address_list_import_job command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.create_address_list_import_job(input)
	return common.execute_aws_command_with_input({ "mailmanager", "create-address-list-import-job" }, input)
end

--- Removes a member from an address list
--- @param input table The input table for the deregister_member_from_address_list command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.deregister_member_from_address_list(input)
	return common.execute_aws_command_with_input({ "mailmanager", "deregister-member-from-address-list" }, input)
end

--- Fetch attributes of an import job
--- @param input table The input table for the get_address_list_import_job command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.get_address_list_import_job(input)
	return common.execute_aws_command_with_input({ "mailmanager", "get-address-list-import-job" }, input)
end

--- Retrieves the details and current status of a specific email archive export job
--- @param input table The input table for the get_archive_export command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.get_archive_export(input)
	return common.execute_aws_command_with_input({ "mailmanager", "get-archive-export" }, input)
end

--- Returns a pre-signed URL that provides temporary download access to the specific email message stored in the archive
--- @param input table The input table for the get_archive_message command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.get_archive_message(input)
	return common.execute_aws_command_with_input({ "mailmanager", "get-archive-message" }, input)
end

--- Returns the textual content of a specific email message stored in the archive
--- @param input table The input table for the get_archive_message_content command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.get_archive_message_content(input)
	return common.execute_aws_command_with_input({ "mailmanager", "get-archive-message-content" }, input)
end

--- Retrieves the details and current status of a specific email archive search job
--- @param input table The input table for the get_archive_search command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.get_archive_search(input)
	return common.execute_aws_command_with_input({ "mailmanager", "get-archive-search" }, input)
end

--- Returns the results of a completed email archive search job
--- @param input table The input table for the get_archive_search_results command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.get_archive_search_results(input)
	return common.execute_aws_command_with_input({ "mailmanager", "get-archive-search-results" }, input)
end

--- Fetch attributes of a member in an address list
--- @param input table The input table for the get_member_of_address_list command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.get_member_of_address_list(input)
	return common.execute_aws_command_with_input({ "mailmanager", "get-member-of-address-list" }, input)
end

--- Lists jobs for an address list
--- @param input table The input table for the list_address_list_import_jobs command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.list_address_list_import_jobs(input)
	return common.execute_aws_command_with_input({ "mailmanager", "list-address-list-import-jobs" }, input)
end

--- Returns a list of email archive export jobs
--- @param input table The input table for the list_archive_exports command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.list_archive_exports(input)
	return common.execute_aws_command_with_input({ "mailmanager", "list-archive-exports" }, input)
end

--- Returns a list of email archive search jobs
--- @param input table The input table for the list_archive_searches command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.list_archive_searches(input)
	return common.execute_aws_command_with_input({ "mailmanager", "list-archive-searches" }, input)
end

--- Lists members of an address list
--- @param input table The input table for the list_members_of_address_list command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.list_members_of_address_list(input)
	return common.execute_aws_command_with_input({ "mailmanager", "list-members-of-address-list" }, input)
end

--- Retrieves the list of tags (keys and values) assigned to the resource
--- @param input table The input table for the list_tags_for_resource command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.list_tags_for_resource(input)
	return common.execute_aws_command_with_input({ "mailmanager", "list-tags-for-resource" }, input)
end

--- Adds a member to an address list
--- @param input table The input table for the register_member_to_address_list command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.register_member_to_address_list(input)
	return common.execute_aws_command_with_input({ "mailmanager", "register-member-to-address-list" }, input)
end

--- Starts an import job for an address list
--- @param input table The input table for the start_address_list_import_job command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.start_address_list_import_job(input)
	return common.execute_aws_command_with_input({ "mailmanager", "start-address-list-import-job" }, input)
end

--- Initiates an export of emails from the specified archive
--- @param input table The input table for the start_archive_export command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.start_archive_export(input)
	return common.execute_aws_command_with_input({ "mailmanager", "start-archive-export" }, input)
end

--- Initiates a search across emails in the specified archive
--- @param input table The input table for the start_archive_search command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.start_archive_search(input)
	return common.execute_aws_command_with_input({ "mailmanager", "start-archive-search" }, input)
end

--- Stops an ongoing import job for an address list
--- @param input table The input table for the stop_address_list_import_job command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.stop_address_list_import_job(input)
	return common.execute_aws_command_with_input({ "mailmanager", "stop-address-list-import-job" }, input)
end

--- Stops an in-progress export of emails from an archive
--- @param input table The input table for the stop_archive_export command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.stop_archive_export(input)
	return common.execute_aws_command_with_input({ "mailmanager", "stop-archive-export" }, input)
end

--- Stops an in-progress archive search job
--- @param input table The input table for the stop_archive_search command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.stop_archive_search(input)
	return common.execute_aws_command_with_input({ "mailmanager", "stop-archive-search" }, input)
end

--- Adds one or more tags (keys and values) to a specified resource
--- @param input table The input table for the tag_resource command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.tag_resource(input)
	return common.execute_aws_command_with_input({ "mailmanager", "tag-resource" }, input)
end

--- Remove one or more tags (keys and values) from a specified resource
--- @param input table The input table for the untag_resource command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.untag_resource(input)
	return common.execute_aws_command_with_input({ "mailmanager", "untag-resource" }, input)
end

return M
