-- AUTOGENERATED FILE - DO NOT EDIT
-- Generated: 2025-04-08
-- AWS Service: marketplace-entitlement-service

local common = require("nvim-aws.wrappers.common")

--- AWS MARKETPLACE-ENTITLEMENT service functions
local M = {}

--- GetEntitlements retrieves entitlement values for a given product
--- @param input table|nil The input table for the get_entitlements command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.get_entitlements(input)
	return common.execute_aws_command_with_input({ "marketplace-entitlement", "get-entitlements" }, input)
end

return M
