-- AUTOGENERATED FILE - DO NOT EDIT
-- AWS Service: savingsplans

local common = require("nvim-aws.wrappers.common")

--- AWS SAVINGSPLANS service functions
local M = {}

--- Creates a Savings Plan
--- @param input table|nil The input table for the create_savings_plan command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.create_savings_plan(input)
	return common.execute_aws_command_with_input({ "savingsplans", "create-savings-plan" }, input)
end

--- Deletes the queued purchase for the specified Savings Plan
--- @param input table|nil The input table for the delete_queued_savings_plan command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.delete_queued_savings_plan(input)
	return common.execute_aws_command_with_input({ "savingsplans", "delete-queued-savings-plan" }, input)
end

--- Describes the rates for the specified Savings Plan
--- @param input table|nil The input table for the describe_savings_plan_rates command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.describe_savings_plan_rates(input)
	return common.execute_aws_command_with_input({ "savingsplans", "describe-savings-plan-rates" }, input)
end

--- Describes the specified Savings Plans
--- @param input table|nil The input table for the describe_savings_plans command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.describe_savings_plans(input)
	return common.execute_aws_command_with_input({ "savingsplans", "describe-savings-plans" }, input)
end

--- Describes the offering rates for the specified Savings Plans
--- @param input table|nil The input table for the describe_savings_plans_offering_rates command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.describe_savings_plans_offering_rates(input)
	return common.execute_aws_command_with_input({ "savingsplans", "describe-savings-plans-offering-rates" }, input)
end

--- Describes the offerings for the specified Savings Plans
--- @param input table|nil The input table for the describe_savings_plans_offerings command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.describe_savings_plans_offerings(input)
	return common.execute_aws_command_with_input({ "savingsplans", "describe-savings-plans-offerings" }, input)
end

--- Lists the tags for the specified resource
--- @param input table|nil The input table for the list_tags_for_resource command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.list_tags_for_resource(input)
	return common.execute_aws_command_with_input({ "savingsplans", "list-tags-for-resource" }, input)
end

--- Returns the specified Savings Plan
--- @param input table|nil The input table for the return_savings_plan command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.return_savings_plan(input)
	return common.execute_aws_command_with_input({ "savingsplans", "return-savings-plan" }, input)
end

--- Adds the specified tags to the specified resource
--- @param input table|nil The input table for the tag_resource command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.tag_resource(input)
	return common.execute_aws_command_with_input({ "savingsplans", "tag-resource" }, input)
end

--- Removes the specified tags from the specified resource
--- @param input table|nil The input table for the untag_resource command
--- @return {success: boolean, data: table|nil, error: string|nil} Result table
function M.untag_resource(input)
	return common.execute_aws_command_with_input({ "savingsplans", "untag-resource" }, input)
end

return M
