-- AUTOGENERATED FILE - DO NOT EDIT
-- Generated: 2025-04-08
-- AWS Service: bedrock-runtime

require("nvim-aws").setup()
local common = require("nvim-aws.wrappers.common")

describe("AWS bedrock-runtime service testing", function()
	it("should generate a cli skeleton for apply-guardrail", function()
		local result = common.execute_aws_command_with_input({ "bedrock-runtime", "apply-guardrail" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for converse", function()
		local result = common.execute_aws_command_with_input({ "bedrock-runtime", "converse" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for converse-stream", function()
		local result = common.execute_aws_command_with_input({ "bedrock-runtime", "converse-stream" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for get-async-invoke", function()
		local result = common.execute_aws_command_with_input({ "bedrock-runtime", "get-async-invoke" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for invoke-model", function()
		local result = common.execute_aws_command_with_input({ "bedrock-runtime", "invoke-model" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for invoke-model-with-bidirectional-stream", function()
		local result = common.execute_aws_command_with_input({ "bedrock-runtime", "invoke-model-with-bidirectional-stream" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for invoke-model-with-response-stream", function()
		local result = common.execute_aws_command_with_input({ "bedrock-runtime", "invoke-model-with-response-stream" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for list-async-invokes", function()
		local result = common.execute_aws_command_with_input({ "bedrock-runtime", "list-async-invokes" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for start-async-invoke", function()
		local result = common.execute_aws_command_with_input({ "bedrock-runtime", "start-async-invoke" })
		assert.is_true(result.success)
	end)

end)