-- AUTOGENERATED FILE - DO NOT EDIT
-- Generated: 2025-04-08
-- AWS Service: dsql

require("nvim-aws").setup()
local common = require("nvim-aws.wrappers.common")

describe("AWS dsql service testing", function()
	it("should generate a cli skeleton for create-cluster", function()
		local result = common.execute_aws_command_with_input({ "dsql", "create-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for delete-cluster", function()
		local result = common.execute_aws_command_with_input({ "dsql", "delete-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for get-cluster", function()
		local result = common.execute_aws_command_with_input({ "dsql", "get-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for list-clusters", function()
		local result = common.execute_aws_command_with_input({ "dsql", "list-clusters" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for list-tags-for-resource", function()
		local result = common.execute_aws_command_with_input({ "dsql", "list-tags-for-resource" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for tag-resource", function()
		local result = common.execute_aws_command_with_input({ "dsql", "tag-resource" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for untag-resource", function()
		local result = common.execute_aws_command_with_input({ "dsql", "untag-resource" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for update-cluster", function()
		local result = common.execute_aws_command_with_input({ "dsql", "update-cluster" })
		assert.is_true(result.success)
	end)

end)