-- AUTOGENERATED FILE - DO NOT EDIT
-- Generated: 2025-04-08
-- AWS Service: marketplace-agreement

require("nvim-aws").setup()
local common = require("nvim-aws.wrappers.common")

describe("AWS marketplace-agreement service testing", function()
	it("should generate a cli skeleton for describe-agreement", function()
		local result = common.execute_aws_command_with_input({ "marketplace-agreement", "describe-agreement" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for get-agreement-terms", function()
		local result = common.execute_aws_command_with_input({ "marketplace-agreement", "get-agreement-terms" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for search-agreements", function()
		local result = common.execute_aws_command_with_input({ "marketplace-agreement", "search-agreements" })
		assert.is_true(result.success)
	end)

end)