-- AUTOGENERATED FILE - DO NOT EDIT
-- Generated: 2025-04-08
-- AWS Service: neptune

require("nvim-aws").setup()
local common = require("nvim-aws.wrappers.common")

describe("AWS neptune service testing", function()
	it("should generate a cli skeleton for add-role-to-db-cluster", function()
		local result = common.execute_aws_command_with_input({ "neptune", "add-role-to-db-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for add-source-identifier-to-subscription", function()
		local result = common.execute_aws_command_with_input({ "neptune", "add-source-identifier-to-subscription" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for add-tags-to-resource", function()
		local result = common.execute_aws_command_with_input({ "neptune", "add-tags-to-resource" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for apply-pending-maintenance-action", function()
		local result = common.execute_aws_command_with_input({ "neptune", "apply-pending-maintenance-action" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for copy-db-cluster-parameter-group", function()
		local result = common.execute_aws_command_with_input({ "neptune", "copy-db-cluster-parameter-group" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for copy-db-cluster-snapshot", function()
		local result = common.execute_aws_command_with_input({ "neptune", "copy-db-cluster-snapshot" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for copy-db-parameter-group", function()
		local result = common.execute_aws_command_with_input({ "neptune", "copy-db-parameter-group" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for create-db-cluster", function()
		local result = common.execute_aws_command_with_input({ "neptune", "create-db-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for create-db-cluster-endpoint", function()
		local result = common.execute_aws_command_with_input({ "neptune", "create-db-cluster-endpoint" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for create-db-cluster-parameter-group", function()
		local result = common.execute_aws_command_with_input({ "neptune", "create-db-cluster-parameter-group" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for create-db-cluster-snapshot", function()
		local result = common.execute_aws_command_with_input({ "neptune", "create-db-cluster-snapshot" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for create-db-instance", function()
		local result = common.execute_aws_command_with_input({ "neptune", "create-db-instance" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for create-db-parameter-group", function()
		local result = common.execute_aws_command_with_input({ "neptune", "create-db-parameter-group" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for create-db-subnet-group", function()
		local result = common.execute_aws_command_with_input({ "neptune", "create-db-subnet-group" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for create-event-subscription", function()
		local result = common.execute_aws_command_with_input({ "neptune", "create-event-subscription" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for create-global-cluster", function()
		local result = common.execute_aws_command_with_input({ "neptune", "create-global-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for delete-db-cluster", function()
		local result = common.execute_aws_command_with_input({ "neptune", "delete-db-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for delete-db-cluster-endpoint", function()
		local result = common.execute_aws_command_with_input({ "neptune", "delete-db-cluster-endpoint" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for delete-db-cluster-parameter-group", function()
		local result = common.execute_aws_command_with_input({ "neptune", "delete-db-cluster-parameter-group" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for delete-db-cluster-snapshot", function()
		local result = common.execute_aws_command_with_input({ "neptune", "delete-db-cluster-snapshot" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for delete-db-instance", function()
		local result = common.execute_aws_command_with_input({ "neptune", "delete-db-instance" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for delete-db-parameter-group", function()
		local result = common.execute_aws_command_with_input({ "neptune", "delete-db-parameter-group" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for delete-db-subnet-group", function()
		local result = common.execute_aws_command_with_input({ "neptune", "delete-db-subnet-group" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for delete-event-subscription", function()
		local result = common.execute_aws_command_with_input({ "neptune", "delete-event-subscription" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for delete-global-cluster", function()
		local result = common.execute_aws_command_with_input({ "neptune", "delete-global-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-db-cluster-endpoints", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-db-cluster-endpoints" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-db-cluster-parameter-groups", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-db-cluster-parameter-groups" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-db-cluster-parameters", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-db-cluster-parameters" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-db-cluster-snapshot-attributes", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-db-cluster-snapshot-attributes" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-db-cluster-snapshots", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-db-cluster-snapshots" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-db-clusters", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-db-clusters" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-db-engine-versions", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-db-engine-versions" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-db-instances", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-db-instances" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-db-parameter-groups", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-db-parameter-groups" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-db-parameters", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-db-parameters" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-db-subnet-groups", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-db-subnet-groups" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-engine-default-cluster-parameters", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-engine-default-cluster-parameters" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-engine-default-parameters", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-engine-default-parameters" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-event-categories", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-event-categories" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-event-subscriptions", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-event-subscriptions" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-events", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-events" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-global-clusters", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-global-clusters" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-orderable-db-instance-options", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-orderable-db-instance-options" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-pending-maintenance-actions", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-pending-maintenance-actions" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for describe-valid-db-instance-modifications", function()
		local result = common.execute_aws_command_with_input({ "neptune", "describe-valid-db-instance-modifications" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for failover-db-cluster", function()
		local result = common.execute_aws_command_with_input({ "neptune", "failover-db-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for failover-global-cluster", function()
		local result = common.execute_aws_command_with_input({ "neptune", "failover-global-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for list-tags-for-resource", function()
		local result = common.execute_aws_command_with_input({ "neptune", "list-tags-for-resource" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for modify-db-cluster", function()
		local result = common.execute_aws_command_with_input({ "neptune", "modify-db-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for modify-db-cluster-endpoint", function()
		local result = common.execute_aws_command_with_input({ "neptune", "modify-db-cluster-endpoint" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for modify-db-cluster-parameter-group", function()
		local result = common.execute_aws_command_with_input({ "neptune", "modify-db-cluster-parameter-group" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for modify-db-cluster-snapshot-attribute", function()
		local result = common.execute_aws_command_with_input({ "neptune", "modify-db-cluster-snapshot-attribute" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for modify-db-instance", function()
		local result = common.execute_aws_command_with_input({ "neptune", "modify-db-instance" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for modify-db-parameter-group", function()
		local result = common.execute_aws_command_with_input({ "neptune", "modify-db-parameter-group" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for modify-db-subnet-group", function()
		local result = common.execute_aws_command_with_input({ "neptune", "modify-db-subnet-group" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for modify-event-subscription", function()
		local result = common.execute_aws_command_with_input({ "neptune", "modify-event-subscription" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for modify-global-cluster", function()
		local result = common.execute_aws_command_with_input({ "neptune", "modify-global-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for promote-read-replica-db-cluster", function()
		local result = common.execute_aws_command_with_input({ "neptune", "promote-read-replica-db-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for reboot-db-instance", function()
		local result = common.execute_aws_command_with_input({ "neptune", "reboot-db-instance" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for remove-from-global-cluster", function()
		local result = common.execute_aws_command_with_input({ "neptune", "remove-from-global-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for remove-role-from-db-cluster", function()
		local result = common.execute_aws_command_with_input({ "neptune", "remove-role-from-db-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for remove-source-identifier-from-subscription", function()
		local result = common.execute_aws_command_with_input({ "neptune", "remove-source-identifier-from-subscription" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for remove-tags-from-resource", function()
		local result = common.execute_aws_command_with_input({ "neptune", "remove-tags-from-resource" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for reset-db-cluster-parameter-group", function()
		local result = common.execute_aws_command_with_input({ "neptune", "reset-db-cluster-parameter-group" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for reset-db-parameter-group", function()
		local result = common.execute_aws_command_with_input({ "neptune", "reset-db-parameter-group" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for restore-db-cluster-from-snapshot", function()
		local result = common.execute_aws_command_with_input({ "neptune", "restore-db-cluster-from-snapshot" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for restore-db-cluster-to-point-in-time", function()
		local result = common.execute_aws_command_with_input({ "neptune", "restore-db-cluster-to-point-in-time" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for start-db-cluster", function()
		local result = common.execute_aws_command_with_input({ "neptune", "start-db-cluster" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for stop-db-cluster", function()
		local result = common.execute_aws_command_with_input({ "neptune", "stop-db-cluster" })
		assert.is_true(result.success)
	end)

end)