-- AUTOGENERATED FILE - DO NOT EDIT
-- Generated: 2025-04-08
-- AWS Service: networkmonitor

require("nvim-aws").setup()
local common = require("nvim-aws.wrappers.common")

describe("AWS networkmonitor service testing", function()
	it("should generate a cli skeleton for create-monitor", function()
		local result = common.execute_aws_command_with_input({ "networkmonitor", "create-monitor" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for create-probe", function()
		local result = common.execute_aws_command_with_input({ "networkmonitor", "create-probe" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for delete-monitor", function()
		local result = common.execute_aws_command_with_input({ "networkmonitor", "delete-monitor" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for delete-probe", function()
		local result = common.execute_aws_command_with_input({ "networkmonitor", "delete-probe" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for get-monitor", function()
		local result = common.execute_aws_command_with_input({ "networkmonitor", "get-monitor" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for get-probe", function()
		local result = common.execute_aws_command_with_input({ "networkmonitor", "get-probe" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for list-monitors", function()
		local result = common.execute_aws_command_with_input({ "networkmonitor", "list-monitors" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for list-tags-for-resource", function()
		local result = common.execute_aws_command_with_input({ "networkmonitor", "list-tags-for-resource" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for tag-resource", function()
		local result = common.execute_aws_command_with_input({ "networkmonitor", "tag-resource" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for untag-resource", function()
		local result = common.execute_aws_command_with_input({ "networkmonitor", "untag-resource" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for update-monitor", function()
		local result = common.execute_aws_command_with_input({ "networkmonitor", "update-monitor" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for update-probe", function()
		local result = common.execute_aws_command_with_input({ "networkmonitor", "update-probe" })
		assert.is_true(result.success)
	end)

end)