-- AUTOGENERATED FILE - DO NOT EDIT
-- Generated: 2025-04-08
-- AWS Service: trustedadvisor

require("nvim-aws").setup()
local common = require("nvim-aws.wrappers.common")

describe("AWS trustedadvisor service testing", function()
	it("should generate a cli skeleton for batch-update-recommendation-resource-exclusion", function()
		local result = common.execute_aws_command_with_input({ "trustedadvisor", "batch-update-recommendation-resource-exclusion" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for get-organization-recommendation", function()
		local result = common.execute_aws_command_with_input({ "trustedadvisor", "get-organization-recommendation" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for get-recommendation", function()
		local result = common.execute_aws_command_with_input({ "trustedadvisor", "get-recommendation" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for list-checks", function()
		local result = common.execute_aws_command_with_input({ "trustedadvisor", "list-checks" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for list-organization-recommendation-accounts", function()
		local result = common.execute_aws_command_with_input({ "trustedadvisor", "list-organization-recommendation-accounts" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for list-organization-recommendation-resources", function()
		local result = common.execute_aws_command_with_input({ "trustedadvisor", "list-organization-recommendation-resources" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for list-organization-recommendations", function()
		local result = common.execute_aws_command_with_input({ "trustedadvisor", "list-organization-recommendations" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for list-recommendation-resources", function()
		local result = common.execute_aws_command_with_input({ "trustedadvisor", "list-recommendation-resources" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for list-recommendations", function()
		local result = common.execute_aws_command_with_input({ "trustedadvisor", "list-recommendations" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for update-organization-recommendation-lifecycle", function()
		local result = common.execute_aws_command_with_input({ "trustedadvisor", "update-organization-recommendation-lifecycle" })
		assert.is_true(result.success)
	end)

	it("should generate a cli skeleton for update-recommendation-lifecycle", function()
		local result = common.execute_aws_command_with_input({ "trustedadvisor", "update-recommendation-lifecycle" })
		assert.is_true(result.success)
	end)

end)